name: Push images to GCR and to Dockerhub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Project
        run: npm run build

      - name: Run Tests
        run: npm run test --watch=false --browsers=ChromeHeadless

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Google Cloud
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_AUTH }}

      - name: Build and Push Docker Image to GCR
        run: |
          docker build -t gcr.io/mythical-harbor-435609-d3/test-landing:1.1.1 .
          docker push gcr.io/mythical-harbor-435609-d3/test-landing:1.1.1


      - name: Build and Push Docker Image to Docker Hub
        run: |
          docker build -t kirillstasiukdev/test_landing_page_angular:1.1.1 .
          docker push kirillstasiukdev/test_landing_page_angular:1.1.1
